CREATE DATABASE IF NOT EXISTS bdpermisos;
USE bdpermisos;

CREATE TABLE CONTRIBUYENTE (
    RUT VARCHAR(12) PRIMARY KEY,
    NOMBRE VARCHAR(50),
    APELLIDO VARCHAR(50),
    NACIONALIDAD VARCHAR(30),
    DIRECCION VARCHAR(80),
    COMUNA VARCHAR(50)
);

CREATE TABLE VEHICULO (
    PATENTE VARCHAR(10) PRIMARY KEY,
    MARCA VARCHAR(40),
    MODELO VARCHAR(40),
    COLOR VARCHAR(30),
    ANIO INT,
    RUT VARCHAR(12),
    FOREIGN KEY (RUT) REFERENCES CONTRIBUYENTE(RUT)
);

CREATE TABLE CONTROL (
    USUARIO VARCHAR(30),
    CLAVE VARCHAR(30)
);

INSERT INTO CONTRIBUYENTE VALUES ('1-1','Allan','Brown','chileno','Av. Principal 100','Santiago');
INSERT INTO CONTRIBUYENTE VALUES ('2-2','Maria','Lopez','chilena','Los Aromos 250','Valparaiso');
INSERT INTO CONTRIBUYENTE VALUES ('3-3','Pedro','Gonzalez','chileno','Calle Norte 80','Concepcion');

INSERT INTO VEHICULO VALUES ('CCBB10','Hyundai','Carretero','Fucsia',2000,'1-1');
INSERT INTO VEHICULO VALUES ('DDFF20','Toyota','Corolla','Blanco',2015,'2-2');
INSERT INTO VEHICULO VALUES ('GGHH30','Suzuki','Swift','Rojo',2018,'3-3');

INSERT INTO CONTROL VALUES ('admin','1234');
